# Arrays multidimensionales

Anteriormente vimos como trabajar con arrays de una dimensión, ahora veamos como se trasladan esos conceptos cuando tienen 2 o más dimensiones.

## Índices 2D

Podemos imaginar un array 2D como una `tabla` con filas y columnas:

In [ ]:
import numpy as np

arr_2d = np.array(([0,5,10], [15,20,25], [30,35,40]))

In [ ]:
arr_2d

Si tenemos dos dimensiones necesitamos dos índices, uno para las filas y otro para las columnas:

In [ ]:
# primera fila
arr_2d[0]

In [ ]:
# primera fila y primera columna
arr_2d[0][0]

In [ ]:
# última fila y última columna
arr_2d[-1][-1]

In [ ]:
arr_2d[-1][0]

In [ ]:
# edición de la primera columna en la última fila
arr_2d[-1][0] = 99

In [ ]:
arr_2d

## Slicing 2D

Podemos utilizr el slicing doblando los indices de inicio y fin separándolos con una coma:

In [ ]:
# subarray con todas las filas y columnas
arr_2d[:,:]

In [ ]:
# subarray de las dos primeras filas
arr_2d[:2,:]

In [ ]:
# subarray de la primera columna
arr_2d[:,:1]

Mediante esta lógica podemos modificar los elementos masivamente:

In [ ]:
# edición masiva de la segunda columna 
arr_2d[:,1:2] = 99

In [ ]:
arr_2d

In [ ]:
# edición masiva de la última fila
arr_2d[-1,:] = 88

In [ ]:
arr_2d

## Fancy index

Esta técnica se basa en pasarle una lista al array haciendo referencia a las filas donde queremos acceder.

In [ ]:
# creamos un array 2d de ceros
arr_2d = np.zeros((5,10))

In [ ]:
arr_2d

In [ ]:
# modificación masiva de la primera, tercera y última fila
arr_2d[[0,2,-1]] = 5

In [ ]:
arr_2d

Podemos consultar el array a voluntad, incluso repitiendo filas:

In [51]:
arr_2d = np.array([0,1,1,1,0])

## Bucles

Podemos recorrer las filas de un array con un bucle `for` como si de una lista se tratase:

In [59]:
arr_2d = np.array(([0,5,10], [15,20,25], [30,35,40]))

for fila in arr_2d:
    print(fila)

[ 0  5 10]
[15 20 25]
[30 35 40]


Utilizando enumeradores podemos sacar el índice de cada posición de la fila y el de la columna y asignarle algo:

In [73]:
for i,fila in enumerate(arr_2d):
    for j,columna in enumerate(fila):
        arr_2d[i][j] = len(fila) * i + j

0
1
2
3
4
5
6
7
8


In [56]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Arrays 3D y más dimensiones

Hasta ahora hemos trabajado los arrays de 1 y 2 dimensiones, ¿será posible hacer lo mismo con 3 o más dimensiones?

El truco para manejar arrays de más dimensiones es anidar niveles de profundidad.

Vamos a recrear los 3 niveles de profundidad paso a paso para un array muy simple de 2x2x2:

In [74]:
# primer nivel con 2 de ancho 
arr_1d = np.array(
    [1, 2]
)

In [75]:
arr_1d

array([1, 2])

In [76]:
# segundo nivel con 2 de ancho y 2 de alto (2*2=4)
arr_2d = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

In [77]:
arr_2d

array([[1, 2],
       [3, 4]])

In [78]:
# tercer nivel con 2 de ancho, 2 de alto y 2 de profundidad (2*2*2=8)
arr_3d = np.array(
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ]
)

In [79]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Con esto tenemos 3 dimensiones pero podemos añadir más.

El concepto es difícil de imaginar, nosotros únicamente percibimos 3 dimensiones pero si lo entendemos como una ramificación dónde para cada elemento hay otra lista con varios elementos, entonces podemos hacernos una idea:

In [80]:
# Cuarto nivel con 2 de ancho, 2 de alto, 2 de profundidad y 2 de... ¿espacio/tiempo? xD
arr_4d = np.array(
    [
        [
            [
                [1, 2],
                [3, 4]
            ],
            [
                [5, 6],
                [7, 8]
            ]
        ],
        [
            [
                [9, 10],
                [11, 12]
            ],
            [
                [13, 14],
                [15, 16]
            ]
        ]
    ]
)

In [81]:
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

Podemos crear arrays multidimensionales con las funciones de pre-generación que ya vimos:

In [82]:
# array 3d de ceros 2x2x2
arr_3d = np.zeros([2,2,2])

In [83]:
arr_3d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [84]:
# array 4d de unos 2x2x2x2
arr_4d = np.ones([2,2,2,2])

In [85]:
arr_4d

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

También podemos utilizar una función llamada `reshape` para reformar las dimensiones y sus tamaños:

In [86]:
# reshape de un rango con 9 elementos a una matriz 3x3
arr_2d = np.arange(9).reshape(3,3)

In [87]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Evidentemente hay que seguir un patrón lógico, el número de elementos tiene que coincidir con el tamaño de las dimensiones multiplicadas:

In [90]:
# esto no funcionará: 9 != 3x3x3
arr_3d = np.arange(9).reshape(3,3,3)

ValueError: cannot reshape array of size 9 into shape (3,3,3)

In [91]:
# esto sí que funcionará: 27 == 3x3x3
arr_3d = np.arange(27).reshape(3,3,3)

In [92]:
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])