# Filtrado de arrays

En esta lección vamos a repasar algunas funciones para filtrar arrays. Para más información sobre las funciones disponibles [la documentación oficial](https://numpy.org/doc/stable/reference/index.html).

Devuelve un array de una dimensión borrando todos los elementos duplicados:

In [3]:
import numpy as np

### Filtrar un array con valores específicos:

Supongamos que tenemos un array temperaturas que contiene las temperaturas registradas en diferentes días:

In [4]:
temperaturas = np.array([28, 23, 28, 27, 23, 31, 18])

Para obtener un nuevo array que solo incluya los días con temperaturas superiores a 27°C, podemos usar la siguiente sintaxis:

In [5]:
dias_calurosos = temperaturas > 25 # crea un array booleano donde True representa los valores superiores a 20°C 
temperaturas_calurosas = temperaturas[dias_calurosos] # utiliza el array booleano como máscara para seleccionar solo los elementos de temperaturas correspondientes a las posiciones donde dias_calurosos es True.

In [6]:
# Resultado
temperaturas_calurosas

array([28, 28, 27, 31])

## Elementos unicos

In [10]:
# aplicamos el filtro unique
np.unique(temperaturas_calurosas)

array([27, 28, 31])

## Filtro in1d

Devuelve un array de una dimensión indicando si los elementos de una lista se encuentran en otro array:

In [34]:
np.in1d([30, 20, 23, 31], temperaturas)

array([ True, False,  True,  True])

### Filtrar un array con base en otro array:

Imagina que tenemos un array nombres con los nombres de los estudiantes y otro array calificaciones con sus calificaciones correspondientes:

In [17]:
nombres = np.array(["Juan", "María", "Pedro", "Ana"])
calificaciones = np.array([8, 9.5, 7, 10])

Para obtener un nuevo array que contenga solo los nombres y calificaciones de los estudiantes que aprobaron (calificación mayor o igual a 7), podemos usar:

In [18]:
# Escribe el código

array([ 8. ,  9.5,  7. , 10. ])

## Filtro where

Sirve para generar un array filtrado a partir de una condición y un valor por defecto:

In [9]:
# generamos un array con números aleatorios
arr_1 = np.random.randint(-5, 5, size=[3,2])

arr_1

array([[ 2,  1],
       [ 0, -2],
       [ 0,  4]])

In [10]:
# creamos un filtro que establece los negativos a 0 - Escribe el código

(array([1], dtype=int64), array([1], dtype=int64))

## Filtros booleanos

Permiten hacer comprobaciones lógicas en los arrays de booleanos:

In [19]:
# definimos un array de booleanos
arr_bool = np.array([True,True,True,False])

In [20]:
# comprobar si todos los elementos del array son True
arr_bool.all()

False

In [21]:
# comprobar si al menos un elementos del array es True
arr_bool.any()

True

También funciona con múltiples dimensiones pasando el eje:

In [22]:
# definimos un array de booleanos 2d
arr_bool_2d = np.array(
    [
        [False, True],
        [False, True],
        [False, True]
    ]
)

arr_bool_2d

array([[False,  True],
       [False,  True],
       [False,  True]])

In [23]:
# comprobar si alguna de las columnas es todo True
arr_bool_2d.all(0)

array([False,  True])

In [24]:
# comprobar si alguna de las filas tiene algún True
arr_bool_2d.any(1)

array([ True,  True,  True])