# Métodos internos

En esta lección vamos a repasar algunos métodos estadísticos y de ordenación que incluyen las instancias de la clase array. Para más información tenéis [la documentación oficial](https://numpy.org/doc/stable/reference/index.html).

## Métodos estadísticos

In [1]:
import numpy as np

# generamos un array de 2*3 con números aleatorios
arr = np.arange(1,7).reshape(2,3)

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
# sumatorio
arr.sum()

21

In [3]:
# media
arr.mean()

3.5

In [4]:
# desviación estándard
arr.std()

1.707825127659933

In [5]:
# varianza
arr.var()

2.9166666666666665

## Métodos de ordenación

In [6]:
# generamos un nuevo array aleatorio
arr = np.random.randint(-10,10,[3,3])

arr

array([[-7,  3,  2],
       [ 5,  0,  2],
       [ 0,  6,  0]])

In [7]:
# Ordenar elementos horizontalmente
arr.sort()

arr

array([[-7,  2,  3],
       [ 0,  2,  5],
       [ 0,  0,  6]])

In [8]:
# Ordenar elementos verticalmente
arr.sort(0)

arr

array([[-7,  0,  3],
       [ 0,  2,  5],
       [ 0,  2,  6]])